### ISSUE TITLE
Sharing pretrained model

### ISSUE THREAD

**Issue by islamtashfiq** [VisionLearningGroup/taskcv-2017-public#1]
Can you share the weights of dilation network that was trained on GTA5 data and/or cityscapes?

**Comment by jhoffman** [comment]
The link for the GTA source dilation model has now been added.

**Comment by islamtashfiq** [comment]
Does the model trained on ImageNet before training on the GTA5 data?

**Comment by jhoffman** [comment]
Yes, this model has been pretrained on ImageNet (challenge data).

**Comment by islamtashfiq** [comment]
Just to be clear, did you use this dilation10_cityscapes_deploy.prototxt for training?

**Comment by jhoffman** [comment]
during training and evaluation the prototxt is programtically generated. See train.py in dilation codebase for an example.
